"""empty message

Revision ID: 2a44bb1ba54f
Revises: 
Create Date: 2020-09-10 16:14:10.137437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a44bb1ba54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblSQ')
    op.drop_table('tblSODetails')
    op.drop_table('tblSQDetails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblSQDetails',
    sa.Column('DocEntry', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DocNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DocDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Cancelled', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DocStatus', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CardCode', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CardName', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('RowNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ItemCode', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ItemName', sa.NVARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Quantity', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('Warehouse', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sales_Employee', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sales_Contact', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Customer_Recipient', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Customer_Number', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isCEF_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isTruck_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isStock_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isPrice_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('SMSNotification', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Remarks', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('Delivery_Date', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ManuallyClosed', sa.NVARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('OpenQty', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True)
    )
    op.create_table('tblSODetails',
    sa.Column('DocEntry', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DocNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DocDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Cancelled', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DocStatus', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CardCode', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CardName', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('RowNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ItemCode', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ItemName', sa.NVARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Quantity', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('Warehouse', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sales_Employee', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sales_Contact', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Customer_Recipient', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Customer_Number', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isCEF_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isTruck_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isStock_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isPrice_Approved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('SMSNotification', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Remarks', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('Delivery_Date', sa.NVARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ManuallyClosed', sa.NVARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('BaseQty', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('BaseDocNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BaseObjtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BaseDocEntry', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('tblSQ',
    sa.Column('DocNum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DocDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('CardCode', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CardName', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ItemCode', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ItemName', sa.NVARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Quantity', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('warehouse', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isApproved', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sales_Employee', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isSent', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cust_number', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recipient', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('isApprovedStock', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isApprovedTruck', sa.NVARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
